### ISSUE TITLE
Docs and code not the same?

### ISSUE THREAD

**Issue by shoesforindustry** [floriankarsten/kirby3-vipsthumbnail#1]
Hi Florian, thanks for this driver, I was looking at writing one myself but had put it off till I could take a more detailed look at the documentation, so it is brilliant that you have already done it!

Just one small question, in the docs you say the defaults are:
"strip default: true - strips metadata from images"
"autoOrient default: false - aplies orientation meta tag if its present (in vips flag --rotate)"

But the code (protected function defaults()) says:
```php
'autoOrient'    => true,
'strip'         => false,
```

**Comment by iskrisis** [comment]
Yes thats a mistake. Fixed in https://github.com/floriankarsten/kirby3-vipsthumbnail/commit/a1e028df4dad3b9ec475fd3983913aa531a06be2
