### ISSUE TITLE
Error on 'thumbs' = NULL

### ISSUE THREAD

**Issue by S1SYPHOS** [floriankarsten/kirby3-vipsthumbnail#4]
The following line contains `option('thumbs')`, but being undefined (meaning `null`, for example on plainkit), this throws an error:

https://github.com/floriankarsten/kirby3-vipsthumbnail/blob/a1e028df4dad3b9ec475fd3983913aa531a06be2/Vipsthumbnail.php#L22

We could check for this first .. I'd be happy to provide a PR, if that's alright?

Cheers,
S1SYPHOS

**Comment by iskrisis** [comment]
Awesome. I use this on one production site without issues so if you can do PR to make this better or atleast tell me what to change so i don't have to think about it than its great!

**Comment by S1SYPHOS** [comment]
Alright! See #5
